name: Scheduled Job

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
      AP_ACCESS_TOKEN: ${{ secrets.AP_ACCESS_TOKEN }}
      AP_URL: ${{ secrets.AP_URL }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21'
    - name: Install dependencies
      run: npm install
    - name: Run publish
      run: node index.js
